#!/usr/bin/env pwsh
#
# OpenWXSDR Python-Only Update Package Builder (PowerShell)
# Creates a timestamped tarball of all Python files in src/ for quick deployment.
#
# Usage:
#   .\build_python_update.ps1
#
# Output (relative to repo root):
#   build\python-update-YYYYMMDD-HHMMSS\openwxsdr-python-YYYYMMDD-HHMMSS.tar.gz
#   build\python-update-YYYYMMDD-HHMMSS\openwxsdr-python-YYYYMMDD-HHMMSS.tar.gz.sha256
#   build\python-update-YYYYMMDD-HHMMSS\install_python_update.sh

$ErrorActionPreference = "Stop"

function Write-Info($msg) { Write-Host "[INFO] $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "[ OK ] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Err($msg)  { Write-Host "[ ERR] $msg" -ForegroundColor Red }

# ── Resolve repo root ──────────────────────────────────────────────────────────
$REPO_ROOT = $PSScriptRoot
$TIMESTAMP = Get-Date -Format "yyyyMMdd-HHmmss"
$PACKAGE_NAME = "openwxsdr-python-$TIMESTAMP"
$BUILD_ROOT = Join-Path $REPO_ROOT "build\python-update-$TIMESTAMP"
$STAGE_ROOT = Join-Path $BUILD_ROOT $PACKAGE_NAME
$TARBALL = Join-Path $BUILD_ROOT "$PACKAGE_NAME.tar.gz"
$INSTALLER = Join-Path $BUILD_ROOT "install_python_update.sh"

Write-Host "================================================================"
Write-Host "  OpenWXSDR Python Update Package Builder (PowerShell)"
Write-Host "================================================================"
Write-Info "Repo root  : $REPO_ROOT"
Write-Info "Build root : $BUILD_ROOT"
Write-Info "Package    : $PACKAGE_NAME"
Write-Host ""

# ── Sanity checks ──────────────────────────────────────────────────────────────
$RequiredPaths = @(
    "$REPO_ROOT\src\openwxsdr_app.py",
    "$REPO_ROOT\src\__init__.py",
    "$REPO_ROOT\src\decoders",
    "$REPO_ROOT\src\output",
    "$REPO_ROOT\src\sdr",
    "$REPO_ROOT\src\webui"
)

foreach ($path in $RequiredPaths) {
    if (-not (Test-Path $path)) {
        Write-Err "Required path missing: $path"
        exit 1
    }
}

# ── Create staging directory ────────────────────────────────────────────────────
Write-Info "Creating staging tree..."
if (Test-Path $BUILD_ROOT) {
    Remove-Item -Recurse -Force $BUILD_ROOT
}
New-Item -ItemType Directory -Path "$STAGE_ROOT\src\decoders" -Force | Out-Null
New-Item -ItemType Directory -Path "$STAGE_ROOT\src\output" -Force | Out-Null
New-Item -ItemType Directory -Path "$STAGE_ROOT\src\sdr" -Force | Out-Null
New-Item -ItemType Directory -Path "$STAGE_ROOT\src\webui" -Force | Out-Null

# ── Copy Python files only ──────────────────────────────────────────────────────
Write-Info "Copying Python source files..."
Copy-Item "$REPO_ROOT\src\openwxsdr_app.py" "$STAGE_ROOT\src\openwxsdr_app.py"
Copy-Item "$REPO_ROOT\src\__init__.py" "$STAGE_ROOT\src\__init__.py"

# Copy all Python files from subdirectories
Get-ChildItem "$REPO_ROOT\src\decoders\*.py" | Copy-Item -Destination "$STAGE_ROOT\src\decoders\"
Get-ChildItem "$REPO_ROOT\src\output\*.py" | Copy-Item -Destination "$STAGE_ROOT\src\output\"
Get-ChildItem "$REPO_ROOT\src\sdr\*.py" | Copy-Item -Destination "$STAGE_ROOT\src\sdr\"
Get-ChildItem "$REPO_ROOT\src\webui\*.py" | Copy-Item -Destination "$STAGE_ROOT\src\webui\"

$TOTAL_FILES = (Get-ChildItem -Path "$STAGE_ROOT\src" -Filter "*.py" -Recurse).Count
Write-Ok "Copied $TOTAL_FILES Python files"

# ── Write installer ─────────────────────────────────────────────────────────────
Write-Info "Generating install_python_update.sh..."

$InstallerContent = @'
#!/usr/bin/env bash
#
# OpenWXSDR Python-Only Update Installer
# Generated by build_python_update.ps1
#
# This script deploys only Python source files to an existing OpenWXSDR installation.
# Config files and templates are NOT modified.
#
# Usage:
#   chmod +x install_python_update.sh
#   sudo ./install_python_update.sh <python-update-tarball.tar.gz> [install-dir]
#
# Default install-dir: /home/pi/OpenWXSDR

set -Eeuo pipefail

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()   { echo -e "${GREEN}[ OK ]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ ERR]${NC} $*" >&2; }

usage() {
    cat <<EOF
Usage:
  sudo ./install_python_update.sh <python-update-tarball.tar.gz> [install-dir]

Arguments:
  python-update-tarball.tar.gz   Path to the Python update archive
  install-dir                    (optional) Target OpenWXSDR installation directory
                                 Default: /home/pi/OpenWXSDR

Examples:
  sudo ./install_python_update.sh openwxsdr-python-20260522-143000.tar.gz
  sudo ./install_python_update.sh openwxsdr-python-20260522-143000.tar.gz /opt/openwxsdr

NOTE: This installer updates ONLY Python source files. Config files and templates
      are preserved unchanged. The OpenWXSDR service will be restarted automatically.
EOF
}

# ── Parse arguments ────────────────────────────────────────────────────────────
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" || $# -lt 1 ]]; then
    usage
    exit 0
fi

TARBALL="$1"
INSTALL_DIR="${2:-/home/pi/OpenWXSDR}"

echo "================================================================"
echo "  OpenWXSDR Python-Only Update Installer"
echo "================================================================"
info "Tarball    : $(basename "$TARBALL")"
info "Install dir: ${INSTALL_DIR}"
echo ""

# ── Validate inputs ────────────────────────────────────────────────────────────
if [[ ! -f "$TARBALL" ]]; then
    err "Tarball not found: $TARBALL"
    exit 1
fi

if [[ ! -d "$INSTALL_DIR" ]]; then
    err "Install directory not found: $INSTALL_DIR"
    err "Create it first or pass the correct path as the second argument."
    exit 1
fi

if [[ ! -d "${INSTALL_DIR}/src" ]]; then
    err "No src/ directory found in ${INSTALL_DIR}"
    err "This may not be a valid OpenWXSDR installation."
    exit 1
fi

# ── Check permissions ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    warn "Not running as root. You may encounter permission errors."
    warn "Consider running: sudo ./install_python_update.sh $*"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        info "Aborted by user."
        exit 0
    fi
fi

# ── Backup current Python files ────────────────────────────────────────────────
BACKUP_DIR="${INSTALL_DIR}/backups/python-backup-$(date +%Y%m%d-%H%M%S)"
info "Creating backup of current Python files..."
mkdir -p "${BACKUP_DIR}/src"

if [[ -d "${INSTALL_DIR}/src" ]]; then
    cp -a "${INSTALL_DIR}/src" "${BACKUP_DIR}/"
    ok "Backup created: ${BACKUP_DIR}"
else
    warn "No src/ directory to backup"
fi

# ── Extract ────────────────────────────────────────────────────────────────────
TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

info "Extracting: $(basename "$TARBALL")"
tar -xzf "$TARBALL" -C "$TMP_DIR"

PAYLOAD_ROOT="$(find "$TMP_DIR" -mindepth 1 -maxdepth 1 -type d | head -n1)"
if [[ -z "$PAYLOAD_ROOT" || ! -d "$PAYLOAD_ROOT" ]]; then
    err "Unable to locate extracted payload directory inside tarball."
    exit 1
fi
info "Payload root: $(basename "$PAYLOAD_ROOT")"

# ── Deploy Python files ────────────────────────────────────────────────────────
info "Deploying Python files to ${INSTALL_DIR}/src..."

# Ensure directories exist
mkdir -p \
    "${INSTALL_DIR}/src/decoders" \
    "${INSTALL_DIR}/src/output" \
    "${INSTALL_DIR}/src/sdr" \
    "${INSTALL_DIR}/src/webui"

# Copy all Python files
cp -v "${PAYLOAD_ROOT}/src/openwxsdr_app.py" "${INSTALL_DIR}/src/openwxsdr_app.py"
cp -v "${PAYLOAD_ROOT}/src/__init__.py"      "${INSTALL_DIR}/src/__init__.py"
cp -v "${PAYLOAD_ROOT}/src/decoders/"*.py    "${INSTALL_DIR}/src/decoders/" 2>/dev/null || true
cp -v "${PAYLOAD_ROOT}/src/output/"*.py      "${INSTALL_DIR}/src/output/" 2>/dev/null || true
cp -v "${PAYLOAD_ROOT}/src/sdr/"*.py         "${INSTALL_DIR}/src/sdr/" 2>/dev/null || true
cp -v "${PAYLOAD_ROOT}/src/webui/"*.py       "${INSTALL_DIR}/src/webui/" 2>/dev/null || true

DEPLOYED_COUNT=$(find "${PAYLOAD_ROOT}/src" -name "*.py" | wc -l)
ok "Deployed ${DEPLOYED_COUNT} Python files"

# ── Service restart ────────────────────────────────────────────────────────────
if command -v systemctl >/dev/null 2>&1; then
    if systemctl list-unit-files 2>/dev/null | grep -q '^openwxsdr\.service'; then
        info "Restarting openwxsdr service..."
        if systemctl restart openwxsdr; then
            ok "Service restarted successfully"
            sleep 2
            if systemctl is-active --quiet openwxsdr; then
                ok "Service is running"
            else
                warn "Service may not have started correctly"
                warn "Check logs: sudo journalctl -u openwxsdr -n 50"
            fi
        else
            err "Service restart failed"
            err "Restart manually: sudo systemctl restart openwxsdr"
            exit 1
        fi
    else
        warn "openwxsdr.service not registered; skipping restart"
        warn "You may need to manually restart the application"
    fi
else
    warn "systemctl not found; skipping service restart"
    warn "You may need to manually restart the application"
fi

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo "================================================================"
ok "Python update installation complete"
echo "================================================================"
info "Backup location: ${BACKUP_DIR}"
info "Deployed files : ${DEPLOYED_COUNT} Python files"
echo ""
info "Next steps:"
echo "  1. Check service status: sudo systemctl status openwxsdr"
echo "  2. View logs: sudo journalctl -u openwxsdr -f"
echo "  3. Access Web UI: http://<raspberry-pi-ip>:5000"
echo ""
'@

Set-Content -Path $INSTALLER -Value $InstallerContent -Encoding UTF8
Write-Ok "Installer written: $INSTALLER"

# ── Create tarball ──────────────────────────────────────────────────────────────
Write-Info "Creating tarball..."

# Check if tar is available (Git for Windows includes it)
if (Get-Command tar -ErrorAction SilentlyContinue) {
    Push-Location $BUILD_ROOT
    tar -czf "$PACKAGE_NAME.tar.gz" $PACKAGE_NAME
    Pop-Location
    Write-Ok "Tarball: $TARBALL"
} else {
    Write-Warn "tar command not found. Install Git for Windows or use WSL."
    Write-Warn "You can manually create the archive from: $STAGE_ROOT"
}

# ── Checksum ────────────────────────────────────────────────────────────────────
if (Test-Path $TARBALL) {
    Write-Info "Generating SHA256 checksum..."
    $hash = Get-FileHash -Path $TARBALL -Algorithm SHA256
    $checksumFile = "$TARBALL.sha256"
    "$($hash.Hash.ToLower())  $PACKAGE_NAME.tar.gz" | Set-Content -Path $checksumFile -Encoding ASCII
    Write-Ok "SHA256 : $checksumFile"
}

# ── Summary ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "================================================================"
Write-Host "  Build complete"
Write-Host "================================================================"
if (Test-Path $TARBALL) {
    Write-Ok "Package : $TARBALL"
} else {
    Write-Warn "Package : Not created (tar command unavailable)"
    Write-Info "Files staged in: $STAGE_ROOT"
}
Write-Ok "Installer : $INSTALLER"
if (Test-Path "$TARBALL.sha256") {
    Write-Ok "Checksum : $TARBALL.sha256"
}
Write-Host ""
Write-Info "To deploy to Raspberry Pi:"
Write-Host "  1. Copy files to Raspberry Pi:"
Write-Host "     scp $BUILD_ROOT\*.tar.gz $BUILD_ROOT\*.sh pi@<raspberry-pi-ip>:/home/pi/"
Write-Host ""
Write-Host "  2. SSH to Raspberry Pi and run:"
Write-Host "     chmod +x /home/pi/install_python_update.sh"
Write-Host "     sudo /home/pi/install_python_update.sh /home/pi/$PACKAGE_NAME.tar.gz"
Write-Host ""
Write-Info "Total Python files: $TOTAL_FILES"
Write-Host "================================================================"
