#!/usr/bin/env bash
#
# OpenWXSDR Python-Only Update Package Builder
# Creates a timestamped tarball of all Python files in src/ for quick deployment.
#
# Usage:
#   chmod +x build_python_update.sh
#   ./build_python_update.sh
#
# Output (relative to repo root):
#   build/python-update-YYYYMMDD-HHMMSS/openwxsdr-python-YYYYMMDD-HHMMSS.tar.gz
#   build/python-update-YYYYMMDD-HHMMSS/openwxsdr-python-YYYYMMDD-HHMMSS.tar.gz.sha256
#   build/python-update-YYYYMMDD-HHMMSS/install_python_update.sh

set -Eeuo pipefail

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()   { echo -e "${GREEN}[ OK ]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ ERR]${NC} $*" >&2; }

# ── Resolve repo root (directory of this script) ──────────────────────────────
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
PACKAGE_NAME="openwxsdr-python-${TIMESTAMP}"
BUILD_ROOT="${REPO_ROOT}/build/python-update-${TIMESTAMP}"
STAGE_ROOT="${BUILD_ROOT}/${PACKAGE_NAME}"
TARBALL="${BUILD_ROOT}/${PACKAGE_NAME}.tar.gz"
INSTALLER="${BUILD_ROOT}/install_python_update.sh"

echo "================================================================"
echo "  OpenWXSDR Python Update Package Builder"
echo "================================================================"
info "Repo root  : ${REPO_ROOT}"
info "Build root : ${BUILD_ROOT}"
info "Package    : ${PACKAGE_NAME}"
echo ""

# ── Sanity checks ─────────────────────────────────────────────────────────────
for f in \
    "${REPO_ROOT}/src/openwxsdr_app.py" \
    "${REPO_ROOT}/src/__init__.py" \
    "${REPO_ROOT}/src/decoders" \
    "${REPO_ROOT}/src/output" \
    "${REPO_ROOT}/src/sdr" \
    "${REPO_ROOT}/src/webui"
do
    if [[ ! -e "$f" ]]; then
        err "Required path missing: $f"
        exit 1
    fi
done

# ── Create staging directory ───────────────────────────────────────────────────
info "Creating staging tree..."
rm -rf "${BUILD_ROOT}"
mkdir -p \
    "${STAGE_ROOT}/src/decoders" \
    "${STAGE_ROOT}/src/output" \
    "${STAGE_ROOT}/src/sdr" \
    "${STAGE_ROOT}/src/webui"

# ── Copy Python files only ─────────────────────────────────────────────────────
info "Copying Python source files..."
cp "${REPO_ROOT}/src/openwxsdr_app.py"    "${STAGE_ROOT}/src/openwxsdr_app.py"
cp "${REPO_ROOT}/src/__init__.py"         "${STAGE_ROOT}/src/__init__.py"

# Copy all Python files from subdirectories
find "${REPO_ROOT}/src/decoders" -name "*.py" -exec cp {} "${STAGE_ROOT}/src/decoders/" \;
find "${REPO_ROOT}/src/output" -name "*.py" -exec cp {} "${STAGE_ROOT}/src/output/" \;
find "${REPO_ROOT}/src/sdr" -name "*.py" -exec cp {} "${STAGE_ROOT}/src/sdr/" \;
find "${REPO_ROOT}/src/webui" -name "*.py" -exec cp {} "${STAGE_ROOT}/src/webui/" \;

# Count files
TOTAL_FILES=$(find "${STAGE_ROOT}/src" -name "*.py" | wc -l)
ok "Copied ${TOTAL_FILES} Python files"

# ── Write installer ────────────────────────────────────────────────────────────
info "Generating install_python_update.sh..."

cat > "${INSTALLER}" << 'INSTALLER_EOF'
#!/usr/bin/env bash
#
# OpenWXSDR Python-Only Update Installer
# Generated by build_python_update.sh
#
# This script deploys only Python source files to an existing OpenWXSDR installation.
# Config files and templates are NOT modified.
#
# Usage:
#   chmod +x install_python_update.sh
#   sudo ./install_python_update.sh <python-update-tarball.tar.gz> [install-dir]
#
# Default install-dir: /home/pi/OpenWXSDR

set -Eeuo pipefail

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()   { echo -e "${GREEN}[ OK ]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ ERR]${NC} $*" >&2; }

usage() {
    cat <<EOF
Usage:
  sudo ./install_python_update.sh <python-update-tarball.tar.gz> [install-dir]

Arguments:
  python-update-tarball.tar.gz   Path to the Python update archive
  install-dir                    (optional) Target OpenWXSDR installation directory
                                 Default: /home/pi/OpenWXSDR

Examples:
  sudo ./install_python_update.sh openwxsdr-python-20260522-143000.tar.gz
  sudo ./install_python_update.sh openwxsdr-python-20260522-143000.tar.gz /opt/openwxsdr

NOTE: This installer updates ONLY Python source files. Config files and templates
      are preserved unchanged. The OpenWXSDR service will be restarted automatically.
EOF
}

# ── Parse arguments ────────────────────────────────────────────────────────────
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" || $# -lt 1 ]]; then
    usage
    exit 0
fi

TARBALL="$1"
INSTALL_DIR="${2:-/home/pi/OpenWXSDR}"

echo "================================================================"
echo "  OpenWXSDR Python-Only Update Installer"
echo "================================================================"
info "Tarball    : $(basename "$TARBALL")"
info "Install dir: ${INSTALL_DIR}"
echo ""

# ── Validate inputs ────────────────────────────────────────────────────────────
if [[ ! -f "$TARBALL" ]]; then
    err "Tarball not found: $TARBALL"
    exit 1
fi

if [[ ! -d "$INSTALL_DIR" ]]; then
    err "Install directory not found: $INSTALL_DIR"
    err "Create it first or pass the correct path as the second argument."
    exit 1
fi

if [[ ! -d "${INSTALL_DIR}/src" ]]; then
    err "No src/ directory found in ${INSTALL_DIR}"
    err "This may not be a valid OpenWXSDR installation."
    exit 1
fi

# ── Check permissions ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    warn "Not running as root. You may encounter permission errors."
    warn "Consider running: sudo ./install_python_update.sh $*"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        info "Aborted by user."
        exit 0
    fi
fi

# ── Backup current Python files ────────────────────────────────────────────────
BACKUP_DIR="${INSTALL_DIR}/backups/python-backup-$(date +%Y%m%d-%H%M%S)"
info "Creating backup of current Python files..."
mkdir -p "${BACKUP_DIR}/src"

if [[ -d "${INSTALL_DIR}/src" ]]; then
    cp -a "${INSTALL_DIR}/src" "${BACKUP_DIR}/"
    ok "Backup created: ${BACKUP_DIR}"
else
    warn "No src/ directory to backup"
fi

# ── Extract ────────────────────────────────────────────────────────────────────
TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

info "Extracting: $(basename "$TARBALL")"
tar -xzf "$TARBALL" -C "$TMP_DIR"

PAYLOAD_ROOT="$(find "$TMP_DIR" -mindepth 1 -maxdepth 1 -type d | head -n1)"
if [[ -z "$PAYLOAD_ROOT" || ! -d "$PAYLOAD_ROOT" ]]; then
    err "Unable to locate extracted payload directory inside tarball."
    exit 1
fi
info "Payload root: $(basename "$PAYLOAD_ROOT")"

# ── Deploy Python files ────────────────────────────────────────────────────────
info "Deploying Python files to ${INSTALL_DIR}/src..."

# Ensure directories exist
mkdir -p \
    "${INSTALL_DIR}/src/decoders" \
    "${INSTALL_DIR}/src/output" \
    "${INSTALL_DIR}/src/sdr" \
    "${INSTALL_DIR}/src/webui"

# Copy all Python files
cp -v "${PAYLOAD_ROOT}/src/openwxsdr_app.py" "${INSTALL_DIR}/src/openwxsdr_app.py"
cp -v "${PAYLOAD_ROOT}/src/__init__.py"      "${INSTALL_DIR}/src/__init__.py"
cp -v "${PAYLOAD_ROOT}/src/decoders/"*.py    "${INSTALL_DIR}/src/decoders/" 2>/dev/null || true
cp -v "${PAYLOAD_ROOT}/src/output/"*.py      "${INSTALL_DIR}/src/output/" 2>/dev/null || true
cp -v "${PAYLOAD_ROOT}/src/sdr/"*.py         "${INSTALL_DIR}/src/sdr/" 2>/dev/null || true
cp -v "${PAYLOAD_ROOT}/src/webui/"*.py       "${INSTALL_DIR}/src/webui/" 2>/dev/null || true

DEPLOYED_COUNT=$(find "${PAYLOAD_ROOT}/src" -name "*.py" | wc -l)
ok "Deployed ${DEPLOYED_COUNT} Python files"

# ── Service restart ────────────────────────────────────────────────────────────
if command -v systemctl >/dev/null 2>&1; then
    if systemctl list-unit-files 2>/dev/null | grep -q '^openwxsdr\.service'; then
        info "Restarting openwxsdr service..."
        if systemctl restart openwxsdr; then
            ok "Service restarted successfully"
            sleep 2
            if systemctl is-active --quiet openwxsdr; then
                ok "Service is running"
            else
                warn "Service may not have started correctly"
                warn "Check logs: sudo journalctl -u openwxsdr -n 50"
            fi
        else
            err "Service restart failed"
            err "Restart manually: sudo systemctl restart openwxsdr"
            exit 1
        fi
    else
        warn "openwxsdr.service not registered; skipping restart"
        warn "You may need to manually restart the application"
    fi
else
    warn "systemctl not found; skipping service restart"
    warn "You may need to manually restart the application"
fi

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo "================================================================"
ok "Python update installation complete"
echo "================================================================"
info "Backup location: ${BACKUP_DIR}"
info "Deployed files : ${DEPLOYED_COUNT} Python files"
echo ""
info "Next steps:"
echo "  1. Check service status: sudo systemctl status openwxsdr"
echo "  2. View logs: sudo journalctl -u openwxsdr -f"
echo "  3. Access Web UI: http://<raspberry-pi-ip>:5000"
echo ""
INSTALLER_EOF

chmod +x "${INSTALLER}"
ok "Installer written: ${INSTALLER}"

# ── Create tarball ─────────────────────────────────────────────────────────────
info "Creating tarball..."
( cd "${BUILD_ROOT}" && tar -czf "${PACKAGE_NAME}.tar.gz" "${PACKAGE_NAME}" )
ok "Tarball: ${TARBALL}"

# ── Checksum ───────────────────────────────────────────────────────────────────
if command -v sha256sum >/dev/null 2>&1; then
    ( cd "${BUILD_ROOT}" && sha256sum "${PACKAGE_NAME}.tar.gz" > "${PACKAGE_NAME}.tar.gz.sha256" )
    ok "SHA256 : ${TARBALL}.sha256"
else
    warn "sha256sum not found; checksum skipped"
fi

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo "================================================================"
echo "  Build complete"
echo "================================================================"
ok "Package : ${TARBALL}"
ok "Installer : ${INSTALLER}"
if [[ -f "${TARBALL}.sha256" ]]; then
    ok "Checksum : ${TARBALL}.sha256"
fi
echo ""
info "To deploy to Raspberry Pi:"
echo "  1. Copy files to Raspberry Pi:"
echo "     scp ${BUILD_ROOT}/*.{tar.gz,sh} pi@<raspberry-pi-ip>:/home/pi/"
echo ""
echo "  2. SSH to Raspberry Pi and run:"
echo "     chmod +x /home/pi/install_python_update.sh"
echo "     sudo /home/pi/install_python_update.sh /home/pi/${PACKAGE_NAME}.tar.gz"
echo ""
info "Total Python files: ${TOTAL_FILES}"
echo "================================================================"
